### ISSUE TITLE
Python error: 

### ISSUE THREAD

**Issue by Tele-Pet** [informeren/qgis-cartogram#2] opened 2015-08-05 18:33 UTC
I copied the *qgis-cartogram-develop* folder into .qgis2/plugins/ and get the following error upon starting up QGIS 2.8:
>Couldn't load plugin qgis-cartogram-develop due to an error when calling 
its classFactory() method

Full error message:
>Traceback (most recent call last):
  File "/Applications/QGIS_28/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/myUserName/.qgis2/python/plugins/qgis-cartogram-develop/__init__.py", line 7, in classFactory
    from .cartogram import Cartogram
  File "/Applications/QGIS_28/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/myUserName/.qgis2/python/plugins/qgis-cartogram-develop/cartogram.py", line 10, in 
    from cartogram_dialog import CartogramDialog
  File "/Applications/QGIS_28/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/myUserName/.qgis2/python/plugins/qgis-cartogram-develop/cartogram_dialog.py", line 6, in 
    os.path.dirname(__file__), 'cartogram_dialog_base.ui'))
  File "/Applications/QGIS_28/QGIS.app/Contents/MacOS/../Resources/python/PyQt4/uic/__init__.py", line 213, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 66, in 
  File "/Applications/QGIS_28/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named qgsfieldcombobox

In Plugins Manager I can see the plugin, but it is highlighted red, with the following error:
>**This plugin is broken**
invalid syntax

**Comment by wvcpw** [comment] 2015-08-05 20:52
Same error in 2.10 Pisa

**Comment by anitagraser** [comment] 2015-08-05 21:13
The issue seems cause by custom widgets which are not loaded correctly. 

I've fixed it locally by compiling the .ui file manually

    C:\Users\anita\.qgis2\python\plugins\qgis-cartogram-develop>pyuic4 -o cartogram_dialog_base.py cartogram_dialog_base.ui

and changing cartogram_dialog.py to 

    import os
    from PyQt4 import QtGui, uic
    from cartogram_dialog_base import Ui_CartogramDialogBase

    class CartogramDialog(QtGui.QDialog, Ui_CartogramDialogBase):
        def __init__(self, parent=None):
            """Constructor. Sets up the user interface from QT Designer."""
            super(CartogramDialog, self).__init__(parent)
            self.setupUi(self)

and the last lines of cartogram_dialog_base.py to

    from qgis.gui import QgsFieldComboBox
    from qgis.gui import QgsMapLayerComboBox

**Comment by Tele-Pet** [comment] 2015-08-05 23:10
Thanks @anitagraser.  I didn't have PyQt4 installed, but once I did, I was able to make the changes your noted and am able to run the plugin now.

**Comment by anitagraser** [comment] 2015-08-06 05:42
Maybe reopen the issue. It really should be fixed so that users don't have to mess around with the code.

**Comment by wulff** [comment] 2015-08-06 07:10
Thanks for reporting this issue.

So far, I have only tested the beta on Linux, but I'll try and get it working on Mac and Windows as well.

**Comment by wulff** [comment] 2015-08-06 09:49
I have modified my makefile to compile the form code (as per Anita's example above) instead of using my own custom code.

The latest version of the plugin has been tested in 2.10 on Linux and 2.8 on Mac OS and seems to work as intended.

**Comment by wvcpw** [comment] 2015-08-06 13:19
Now works on Windows in 2.10 as well.

**Comment by Tele-Pet** [comment] 2015-08-06 13:35
Now working for me on Mac, Yosemite 10.10.4, including QGIS Pisa(2.10.1) and Wein(2.8.2).

**Comment by wulff** [comment] 2015-08-07 16:26
@Tele-Pet good to hear!

I have submitted version 1.0 of the plugin to the plugin repository.

**Closed by wulff** 2015-08-07 16:26 UTC
